apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joseph314c-nginx-hc
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  source:
    #repoURL: oci://registry-1.docker.io/bitnamicharts/nginx  # error. OCI registry path
    repoURL: https://charts.bitnami.com/bitnami  # Official Helm repo
    targetRevision: 19.0.2  # Chart version
    chart: nginx  # Chart name (only needed if repoURL points to a repo, not a full OCI path)
    helm:
      releaseName: nginx-hc
      valueFiles:
        #- /manifests/joseph-nginx-hc/values2.yaml  # Path relative to repo root
        - $values/manifests/joseph-nginx-hc/values.yaml
    repoURL: https://github.com/slim-sandbox/argocd-demo.git   #git@github.com:joseph03/sctp-wk24-3.14argocd.git  #
    #targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: joseph314c-ns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true