apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joseph314cc-nginx-hc
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  source:
    # can apply successfully
    repoURL: git@github.com:joseph03/sctp-wk24-3.14argocd.git
    targetRevision: main  # or your actual branch name (not HEAD)
    path: manifests/joseph-nginx-hc
    helm:
      releaseName: nginx-hc
      valueFiles:
        - values.yaml  # Relative to the `path` above
  destination:
    server: https://kubernetes.default.svc
    namespace: joseph314cc-ns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
