apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: joseph314c-nginx-hc
 finalizers:
 - resources-finalizer.argocd.argoproj.io
spec:
 project: default
 sources:
 - repoURL: registry-1.docker.io/bitnamicharts
   chart: nginx
   targetRevision: 19.0.2
   helm:
     releaseName: nginx-hc
     valueFiles:
     - $values/manifests/joseph-nginx-hc/values.yaml
   # if values.yaml is used: Failed sync attempt to : one or more objects failed to apply, 
   # reason: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: 
   # host "nginx-hc.sctp-sandbox.com" and path "/" is already defined in ingress demo/nginx-hc
 - repoURL: "git@github.com:joseph03/sctp-wk24-3.14argocd.git" 
   targetRevision: main
   ref: values
 destination:
   server: https://kubernetes.default.svc
   #namespace: demo #work 
   namespace: joseph314c-ns  # work
 syncPolicy:
   syncOptions:
     - CreateNamespace=true
   automated:
     prune: true
     selfHeal: true